const today = new Date();
const currentYear = today.getFullYear();
const loginYear = 2021;

export const usersModule = {
  labelsList: [
    { id: 1, name: 'Banking', slug: 'banking', color: '#FF8C00' },
    { id: 2, name: 'Company', slug: 'roles', color: '#00C4B4' },
    { id: 3, name: 'Payments', slug: 'payments', color: '#0F9AF7' },
  ],

  usersList: [
    {
      id: 1457690400,
      name: 'Alex Dolgove',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'alex-dolgove@example.com',
      phones: [{ phone: '(215)-659-7529', label: 'Home' }],
      address: 'CEO',
      starred: false,
      roles: 'TCS',
      labels: [2],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 1, 1),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690401,
      name: 'Chelsea Johns',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'chelsea-johnss@example.com',
      phones: [{ phone: '(215)-659-7529', label: 'home' }],
      address: 'CFO',
      starred: false,
      roles: 'Infosys',
      labels: [2, 1],
      status: 'suspended',
      suspendedBy: 'Admin',
      suspendedAt: new Date(currentYear, 1, 1),
      lastLoginAt: new Date(loginYear, 2, 17),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690402,
      name: 'Domnic Brown',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'd@yahoo.com',
      phones: [{ phone: '(215)-748-7855', label: 'home' }],
      address: 'Designer',
      starred: false,
      roles: 'Accenture',
      labels: [3],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 6, 6),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690403,
      name: 'Domnic Harris',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'domenic@yahoo.com',
      phones: [{ phone: '(215)-659-7529', label: 'home' }],
      address: 'PHP Developer',
      starred: false,
      roles: 'Pizza Hut',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 5, 20),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690404,
      name: 'Garry Sobars',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'garry-sobars@example.com',
      phones: [{ phone: '(215)-659-8965', label: 'home' }],
      address: 'HR Manager',
      starred: true,
      roles: 'Dominos',
      labels: [],
      status: 'suspended',
      suspendedBy: 'Admin',
      suspendedAt: new Date(currentYear, 1, 1),
      lastLoginAt: new Date(loginYear, 5, 30),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690405,
      name: 'Jeson Born',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'jeson-born@example.com',
      phones: [{ phone: '(215)-876-5434', label: 'home' }],
      address: 'Marketing Head',
      starred: false,
      roles: 'Subway',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 6, 5),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690406,
      name: 'Jimmy Jo',
      dpUrl: 'https://via.placeholder.com/150g',
      email: 'jimmy-jo@example.com',
      phones: [{ phone: '(215)-659-7529', label: 'home' }],
      address: 'BDO',
      starred: true,
      roles: 'Honda',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 4, 12),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690407,
      name: 'John Smith',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'john-smith@example.com',
      phones: [{ phone: '(215)-456-2346', label: 'home' }],
      address: 'CCO',
      starred: false,
      roles: 'TVS',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 4, 16),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690408,
      name: 'Jonathan Modano',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'jonathan-modano@example.com',
      phones: [{ phone: '(215)-278-4357', label: 'home' }],
      address: 'Developer',
      starred: true,
      roles: 'Hero',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 3, 21),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690409,
      name: 'Kadir M',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'kadir-m@example.com',
      phones: [{ phone: '(215)-286-0788', label: 'home' }],
      address: 'UI-UX Designer',
      starred: false,
      roles: 'Hyundai',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 3, 19),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690410,
      name: 'Ken Ramirez',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'ken-remirez@example.com',
      phones: [{ phone: '(215)-586-4676', label: 'home' }],
      address: 'CEO',
      starred: false,
      roles: 'Maruti',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 5, 11),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690500,
      name: 'Michael Dogov',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'michael-dogov@example.com',
      phones: [{ phone: '(215)-659-7529', label: 'home' }],
      address: 'CEO',
      starred: false,
      roles: 'Chevrolet',
      labels: [],
      status: 'suspended',
      suspendedBy: 'Admin',
      suspendedAt: new Date(currentYear, 1, 1),
      lastLoginAt: new Date(loginYear, 2, 21),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690501,
      name: 'Stella Johnson',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'stella-johnson@example.com',
      phones: [{ phone: '(215)-745-2345', label: 'home' }],
      address: 'CFO',
      starred: false,
      roles: 'Morgan Garrage',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 3, 13),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690502,
      name: 'Steve Smith',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'steve-smith@example.com',
      phones: [{ phone: '(215)-748-3265', label: 'home' }],
      address: 'Designer',
      starred: false,
      roles: 'Tata',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 2, 23),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690503,
      name: 'Noah Owens',
      dpUrl: 'https://via.placeholder.com/150',
      email: 'noah-owens@example.com',
      phones: [{ phone: '(215)-756-3465', label: 'home' }],
      address: 'PHP Developer',
      starred: false,
      Company: 'Levis',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 3, 9),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690404,
      name: 'Ellen Manning',
      dpUrl: '',
      email: 'ellen-manning@example.com',
      phones: [{ phone: '(215)-659-3246', label: 'home' }],
      address: 'HR Manager',
      starred: true,
      roles: 'John Players',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 2, 26),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690505,
      name: 'Angel Jones',
      dpUrl: '',
      email: 'angel-jones@example.com',
      phones: [{ phone: '(215)-876-3246', label: 'home' }],
      address: 'Marketing Head',
      starred: false,
      roles: 'Jaguar',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 5, 18),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690506,
      name: 'Dollie Norton',
      dpUrl: '',
      email: 'dollie-norton@example.com',
      phones: [{ phone: '(215)-785-0967', label: 'home' }],
      address: 'BDO',
      starred: true,
      roles: 'Reliance',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 6, 2),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690507,
      name: 'Joshua Brian',
      dpUrl: '',
      email: 'joshua-brian@example.com',
      phones: [{ phone: '(215)-456-0677', label: 'home' }],
      address: 'CCO',
      starred: false,
      roles: 'Flipkart',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 6, 1),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690508,
      name: 'Amay Mathur',
      dpUrl: '',
      email: 'amay-mathur@example.com',
      phones: [{ phone: '(215)-278-5475', label: 'home' }],
      address: 'Developer',
      starred: true,
      roles: 'Snapdeal',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 6, 4),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690509,
      name: 'Chris Mathew',
      dpUrl: '',
      email: 'chris-mathew@example.com',
      phones: [{ phone: '(215)-286-0456', label: 'home' }],
      address: 'UI-UX Designer',
      starred: false,
      roles: 'Amazon',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 5, 28),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
    {
      id: 1457690510,
      name: 'Nikki Johnson',
      dpUrl: '',
      email: 'nikki-johnson@example.com',
      phones: [{ phone: '(215)-586-2355', label: 'home' }],
      address: 'CEO',
      starred: false,
      roles: 'Myntra',
      labels: [],
      status: 'active',
      suspendedBy: 'Admin',
      suspendedAt: new Date(),
      lastLoginAt: new Date(loginYear, 1, 14),
      createdAt: new Date(currentYear, 1, 1),
      updatedAt: new Date(currentYear, 1, 1),
    },
  ],
};
